# Generated by Django 4.2.7 on 2026-02-24 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.job')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'job_seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viewed_job',
                'ordering': ['-viewed_at'],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
